---
title: "Tidying"
author: "Rhea Ehresmann"
date: "May 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
```

Read in data from the [KNB]
```{r}

catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
```
Selected columns and renamed them
```{r}
catch_df <- catch_df %>%
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)  %>% 
  gather(species, catch, -Region, -Year)%>%
  rename(catch_thousands=catch)
```
Found a typo in original data, corrected it, converted 'catch_thousands' column to numeric, and created
a new column with units # of fish. 
```{r}
catch_df <- catch_df %>%
  mutate(catch_thousands = ifelse(catch_thousands =="I", 1, catch_thousands)) %>%
  mutate(catch_thousands = as.integer(catch_thousands)) %>%
  mutate(catch = catch_thousands * 1000) 

head(catch_df, 30)
```

# Analysis

```{r}
catch_df %>%
  group_by(species, Year) %>%
  summarize(mean_catch=mean(catch), num_obs=n())  
```

```{r}
catch_df %>%
  filter(species == "Chinook" ) %>%
  group_by(Region) %>%
  summarise(mean_catch = mean(catch)) %>%
  arrange(mean_catch)
```













